apiVersion: v1
kind: Pod
metadata:
  name: libquantum2
  labels:
    notcategory: catC
spec:
  containers:
  - image: jmmisd/testspec:1.0.0
    command: ["/bin/bash"]
    args: ["-c" , "sleep 9999999999999999"]
    name: spec-ctn1
  - image: jmmisd/testspec:1.0.0
    command: ["/bin/bash"]
    args: ["-c" , "sleep 9999999999999999"]
    name: spec-ctn2
  restartPolicy: "Never"
