apiVersion: v1
kind: Pod
metadata:
  name: poda1
  namespace: cpuman
  labels:
    category: catA
    plugin: random
spec:
  schedulerName: default-scheduler
  containers:
  - name: poda1
    image: k8s.gcr.io/pause:3.2
